apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: job-portal-ingress
  namespace: job-portal
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      # Auth Service
      - path: /api/auth
        pathType: Prefix
        backend:
          service:
            name: auth-service
            port:
              number: 5000
      
      # User Service
      - path: /api/user
        pathType: Prefix
        backend:
          service:
            name: user-service
            port:
              number: 5002

      # Job Service
      - path: /api/job
        pathType: Prefix
        backend:
          service:
            name: job-service
            port:
              number: 5003

      # Payment Service
      - path: /api/payment
        pathType: Prefix
        backend:
          service:
            name: payment-service
            port:
              number: 5004

      # Utils Service
      - path: /api/utils
        pathType: Prefix
        backend:
          service:
            name: utils-service
            port:
              number: 5001

      # Interview Service
      - path: /api/interview
        pathType: Prefix
        backend:
          service:
            name: interview-service
            port:
              number: 5005

      # Frontend (Root) - Catch all
      - path: /
        pathType: Prefix
        backend:
          service:
            name: frontend-service
            port:
              number: 80
